### ISSUE TITLE
Can't compile with Arduino 1.6.x

### ISSUE THREAD

**Issue by KorkyraBoyCRO** [robotastic/ANCS-Library#7]
Hi...i noticed that this code can't compile with new Arduino version...i tried everything to compile it successfully. So i installed older version of Arduino (1.0.x) and it compiles now without error..Is this possible to fix so it can compile on new version?

**Comment by robotastic** [comment]
Hmm... I just downloaded 1.6 and I am having trouble too. I will see what I can do to fix it.

**Comment by KorkyraBoyCRO** [comment]
ok thx and please let me know cause i am trying to make smartwatch and this code is an excellent starting point...btw not related to this issue but do u know how to set time on arduino by connecting to phone

**Comment by robotastic** [comment]
It should be working with 1.6 with the latest commit. I don't think ancs sends out the current time. You might have to write your own app.

**Comment by KorkyraBoyCRO** [comment]
Thank u for your quick reply :)

**Comment by KorkyraBoyCRO** [comment]
hi i have i new issue here..i have posted it  so can u have a look at it please...thank u
